
> [!abstract] Introduction
> ## About Pytorch

**What is Pytorch?**
- Upgrade of NumPy - with **GPU acceleration**
- Automatic differentiation feature - for **neural networks**

**Goal of this note:**

- Understand Pytorch's **Tensor** and **Networks**.
- Train a small neural network!

Python notebooks can be found in the same directory.

In [2]:
import torch
import numpy as np

print("PyTorch version:", torch.__version__)
print("NumPy version:", np.__version__)

PyTorch version: 2.9.1+cpu
NumPy version: 2.4.1


> [!quote] Definition
> ## Tensors

**Tensors** represents matrices/arrays in memory. It is used to encode inputs, outputs and parameters of a model. It's very similar to `np.array`, but it can run on **GPU/NPUs**.

![[2 - Tensors|100%]]

### Initialize Tensors

In [2]:
data = [[1, 2], [3, 4]]

# Intialize from python array
data_tensor = torch.tensor(data)
print(f"Tensor: \n{data_tensor}")

# From numpy array
np_array = np.array(data)
np_tensor = torch.from_numpy(np_array)

Tensor: 
tensor([[1, 2],
        [3, 4]])


### Copy Tensors

In [1]:
# Create a copy (independent memory)
data_tensor_copy = data_tensor.clone()
# Copy without gradients
data_tensor_copy = data_tensor.detach().clone()

### Construct matching other tensors

In [1]:
# retians the shape and data type of data_tensor

tensor_ones = torch.ones_like(data_tensor) # Ones tensor
tensor_zeros = torch.zeros_like(data_tensor) # Zeros tensor
tensor_rand = torch.rand_like(data_tensor, dtype=torch.float) # Random Tensor, overwrites datatype to float
print(f"Ones Tensor: \n{tensor_ones}\nZeros Tensor: \n{tensor_zeros}\nRand Tensor: \n{tensor_rand}\n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])
Zeros Tensor: 
tensor([[0, 0],
        [0, 0]])
Rand Tensor: 
tensor([[0.4883, 0.4179],
        [0.9721, 0.7014]])



### Construct as shape

In [1]:
shape = (2, 3) # 2-rows x 3-columns matrix
rand_tensor = torch.rand(shape) # All random floating point numbers
ones_tensor = torch.ones(shape) # All integer ones
zeros_tensor = torch.zeros(shape) # All zeros
# Default type is float

print(f"Random Tensor: \n{rand_tensor}")
print(f"Ones Tensor: \n{ones_tensor}")
print(f"Zeros Tensor: \n{zeros_tensor}")

Random Tensor: 
tensor([[0.8215, 0.6339, 0.1332],
        [0.8577, 0.3097, 0.9419]])
Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


> [!info] Info
> ## Attributes of Tensors

The attribute of a tensor includes:
- Its **shape** (e.g. `3x3`, `10000x1`)
- Its **datatype** (e.g. `int`, `float8`, `float32`)
- The **device** at which the tensor is stored

![[3 - Attributes of Tensors|100%]]

In [1]:
print(f"Shape of Random Tensor: {rand_tensor.shape}")
print(f"Datatype of Random Tensor: {rand_tensor.dtype}")
print(f"Random Tensor is stored at: {rand_tensor.device}")

Shape of Random Tensor: torch.Size([2, 3])
Datatype of Random Tensor: torch.float32
Random Tensor is stored at: cpu


> [!hint] Hint
> ## Tensor Operations

A full list of tensor operations is here: [torch — PyTorch 2.9 documentation](https://docs.pytorch.org/docs/stable/torch.html). All of them can be performed on GPU and is accelerated.

In [5]:
tensor = torch.ones(6, 6)
if torch.cuda.is_available():
	tensor = tensor.to('cuda:0')
print(f"Tensor is stored on: {tensor.device}")

Tensor is stored on: cpu


Indexing and slicing like numpy:

In [13]:
tensor[0, 1] = 1
tensor[1,:] = 2
print(tensor)

Row with index 1: tensor([2., 2., 2., 2., 2., 2.])
Column with index 1: tensor([1., 2., 3., 0., 0., 0.])
tensor([[0., 1., 0., 0., 0., 0.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 0., 0., 0., 0.],
        [0., 0., 0., 4., 4., 4.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


--- start-multi-column: ExampleRegion1  
```column-settings  
number of columns: 2  
largest column: left  
```

Text displayed in column 1.

--- end-column ---

Text displayed in column 2.

--- end-multi-column