# 1. Tensors

### 1.1 Intialization

In [1]:
import torch
import numpy as np

print("PyTorch version:", torch.__version__)
print("NumPy version:", np.__version__)

PyTorch version: 2.9.1+cpu
NumPy version: 2.3.5


In [ ]:
# Initialize from python array
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)

# Initialize from a numpy array
np_array = np.array(data)
np_tensor = torch.from_numpy(np_array)

# Copy from other tensor
data_tensor_copy = data_tensor.clone()

# Construct to match other tensors
tensor_ones = torch.ones_like(data_tensor) # retians the shape and data type of data_tensor 
tensor_zeros = torch.zeros_like(data_tensor) # Zero tensor
print(f"Ones Tensor: \n{tensor_ones}\nZeros Tensor: \n{tensor_zeros}\n")
tensor_rand = torch.rand_like(data_tensor, dtype=torch.float) # Overwrites datatype to float

# Construct as shape
shape = (2, 3) # 2-rows x 3-columns matrix
rand_tensor = torch.rand(shape) # All random floating point numbers
ones_tensor = torch.ones(shape) # All integer ones
zeros_tensor = torch.zeros(shape) # All zeros
# Default type is float

print(f"Random Tensor: \n{rand_tensor}")
print(f"Ones Tensor: \n{ones_tensor}")
print(f"Zeros Tensor: \n{zeros_tensor}")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])
Zeros Tensor: 
tensor([[0, 0],
        [0, 0]])

Random Tensor: 
tensor([[0.3884, 0.2158, 0.8587],
        [0.5666, 0.0327, 0.0639]])
Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 1.2 Attributes of Tensors

The attributes of a tensor include:
- Its **shape** (e.g. `2x3`, `5x1`, `100000x1`)
- Its **datatype** (e.g. `int`, `float`, `float8`, `float32`)
- The **device** at which the tensor is stored on

In [10]:
print(f"Shape of Random Tensor: {rand_tensor.shape}")
print(f"Datatype of Random Tensor: {rand_tensor.dtype}")
print(f"Random Tensor is stored at: {rand_tensor.device}")

Shape of Random Tensor: torch.Size([2, 3])
Datatype of Random Tensor: torch.float32
Random Tensor is stored at: cpu
